feat: Add gitleaks

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,9 +1,21 @@
 #!/bin/bash
 
+# Run gitleaks to scan for secrets in staged files
+# Using globally installed gitleaks via Homebrew
+
+gitleaks git --config gitleaks.toml  --exit-code 1
+
+# Check if gitleaks failed
+if [ $? -ne 0 ]; then
+    echo "❌ Gitleaks found secrets in staged files. Commit aborted."
+    exit 1
+fi
+
 # Load environment variables from .env file
 if [ -f .env ]; then
     export $(grep -v '^#' .env | xargs)
 fi
+
 
 # Check if DISABLE_PRE_COMMIT_LINT is not set to true
 if [ "$DISABLE_PRE_COMMIT_LINT" != "true" ]; then
